name: skenteas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  build_runner: ^2.10.5
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_sign_in: ^7.2.0
  grpc: ^5.1.0
  logger: ^2.6.2
  protobuf: ^6.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.4

flutter:
  uses-material-design: true
  assets:
    - .env
