 cleanup_preview:
    if: "${{ github.event.action == 'closed' }}"
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Cleanup Firebase Preview Channel
        run: |
          firebase hosting:channel:delete \
            --project skenteas \
            --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}" \
            --force \
            $(git rev-parse --short HEAD)
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks