name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
  REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
  FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}

jobs:
  build_and_deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build for Production
        run: |
          flutter build web --release \
            --dart-define=SERVER_HOST=$SERVER_HOST \
            --dart-define=NGINX_PORT=${{ secrets.NGINX_PORT }} \
            --dart-define=ACCESS_TOKEN_KEY=$ACCESS_TOKEN_KEY \
            --dart-define=REFRESH_TOKEN_KEY=$REFRESH_TOKEN_KEY \
            --dart-define=FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID \
            --target=lib/bin/prod_skenteas.dart
            
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project YOUR_PROJECT_ID --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"